export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS';
export const CREATE_LANGUAGE_SUCCESS = 'CREATE_LANGUAGE_SUCCESS';
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const LOAD_TRANSLATIONS_SUCCESS = 'LOAD_TRANSLATIONS_SUCCESS';
export const UPDATE_TRANSLATION_SUCCESS = 'UPDATE_TRANSLATION_SUCCESS';
export const CREATE_TRANSLATION_SUCCESS = 'CREATE_TRANSLATION_SUCCESS';
export const DELETE_TRANSLATION_SUCCESS = 'DELETE_TRANSLATION_SUCCESS';

export const LOAD_QUERIES_SUCCESS = 'LOAD_QUERIES_SUCCESS';
export const UPDATE_QUERY_SUCCESS = 'UPDATE_QUERY_SUCCESS';
export const CREATE_QUERY_SUCCESS = 'CREATE_QUERY_SUCCESS';
export const DELETE_QUERY_SUCCESS = 'DELETE_QUERY_SUCCESS';

export const LOAD_TERMS_SUCCESS = 'LOAD_TERMS_SUCCESS';
export const CREATE_TERM_SUCCESS = 'CREATE_TERM_SUCCESS';


export const LOAD_BASIC_FORM_QUERY_SUCCESS = 'LOAD_BASIC_FORM_QUERY_SUCCESS';
export const LOAD_LINKEDIN_FORM_QUERY_SUCCESS = 'LOAD_LINKEDIN_FORM_QUERY_SUCCESS';
